// Hard word bank for the Car Collection unlock challenge.
// These words are above the champion difficulty level and are
// GUARANTEED never to appear in any race word bank.
//
// Selected from grades 4-6 Dolch/Fry sight words + common challenging words.
// All lowercase, unique, and verified against race word banks.

export const CAR_CHALLENGE_WORDS = [
  'achieve',
  'ancient',
  'atmosphere',
  'barrier',
  'brilliant',
  'calculate',
  'champion',
  'colossal',
  'companion',
  'conquer',
  'courage',
  'crystal',
  'defend',
  'destiny',
  'diamond',
  'discover',
  'eclipse',
  'elegant',
  'emerald',
  'endurance',
  'explorer',
  'fantastic',
  'fortress',
  'freedom',
  'gallery',
  'genuine',
  'glacier',
  'gravity',
  'harmony',
  'horizon',
  'ignite',
  'imagine',
  'journey',
  'justice',
  'kingdom',
  'legend',
  'liberty',
  'magnificent',
  'marvel',
  'mechanical',
  'miracle',
  'mystery',
  'natural',
  'observe',
  'optical',
  'oxygen',
  'passage',
  'phantom',
  'pioneer',
  'precision',
  'protect',
  'pursuit',
  'radiant',
  'reflect',
  'rescue',
  'rhythm',
  'sapphire',
  'shadow',
  'shelter',
  'signal',
  'skeleton',
  'solar',
  'sparkle',
  'splendid',
  'stadium',
  'strategy',
  'supreme',
  'surface',
  'tactics',
  'temperature',
  'thunder',
  'titanium',
  'tornado',
  'triumph',
  'ultimate',
  'universe',
  'velocity',
  'venture',
  'victory',
  'volcano',
  'warrior',
  'whisper',
] as const

export const CAR_CHALLENGE_WORD_COUNT = 5